import type {Metadata} from 'next'
import React, {ReactNode} from 'react';
import {Inter} from 'next/font/google'
import ProvidersWrapper from './ProvidersWrapper'
import {Navbar} from "@/components";

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Deliverar',
    description: 'Generated by create next app',
}

export default function RootLayout({children}: {
    children: ReactNode
}) {
    return (
        <html lang="es">
        <body className={inter.className}>
        <ProvidersWrapper>
            <Navbar/>
            {children}
        </ProvidersWrapper>
        </body>
        </html>
    )
}
