import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import ProvidersWrapper from './ProvidersWrapper'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Deliverar',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="es">
    <body className={inter.className}>
    <ProvidersWrapper>
        {children}
    </ProvidersWrapper>
    </body>
    </html>
  )
}
