import type {Metadata} from 'next'
import React, {ReactNode} from 'react';
import ProvidersWrapper from './ProvidersWrapper'
import {Navbar} from "@/components";

export const metadata: Metadata = {
    title: 'Deliverar',
    description: 'Generated by create next app',
}

export default function RootLayout({children}: {
    children: ReactNode
}) {
    return (
        <html lang="es">
        <body>
        <ProvidersWrapper>
            <Navbar/>
            {children}
        </ProvidersWrapper>
        </body>
        </html>
    )
}
